# Generated by Django 4.2.7 on 2026-03-24 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'event_categories',
                'db_table_comment': 'Справочник категорий',
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField()),
                ('complexity_coef', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'events',
                'db_table_comment': 'Мероприятия',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('value', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'settings',
                'db_table_comment': 'Глобальные настройки системы',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'tags',
                'db_table_comment': 'Теги для облака тегов',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=20)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('is_approved', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'db_table_comment': 'Все пользователи системы',
            },
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.users')),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('total_points', models.IntegerField(blank=True, null=True)),
                ('category_breakdown', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'leaderboard',
                'db_table_comment': 'Кэш топ-100 участников',
            },
        ),
        migrations.CreateModel(
            name='OrganizerProfiles',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.users')),
                ('trust_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('events_count', models.IntegerField(blank=True, null=True)),
                ('common_prizes', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'organizer_profiles',
                'db_table_comment': 'Дополнительная информация об организаторах',
            },
        ),
        migrations.CreateModel(
            name='ParticipantProfiles',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.users')),
                ('total_points', models.IntegerField(blank=True, null=True)),
                ('current_rank', models.IntegerField(blank=True, null=True)),
                ('level', models.CharField(blank=True, max_length=50, null=True)),
                ('points_to_next', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'participant_profiles',
                'db_table_comment': 'Дополнительная информация об участниках',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.SmallIntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.events')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='feedback_organizer_set', to='api.users')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.users')),
            ],
            options={
                'db_table': 'feedback',
                'db_table_comment': 'Отзывы участников на организаторов',
            },
        ),
        migrations.AddField(
            model_name='events',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.users'),
        ),
        migrations.CreateModel(
            name='EventPrizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prize_type', models.CharField(max_length=50)),
                ('points', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.events')),
            ],
            options={
                'db_table': 'event_prizes',
                'db_table_comment': 'Призы, привязанные к мероприятиям',
            },
        ),
        migrations.CreateModel(
            name='EventParticipants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('confirmation_method', models.CharField(blank=True, max_length=10, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('points_earned', models.IntegerField(blank=True, null=True)),
                ('registered_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_by', models.ForeignKey(blank=True, db_column='confirmed_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='eventparticipants_confirmed_by_set', to='api.users')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.events')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.users')),
            ],
            options={
                'db_table': 'event_participants',
                'db_table_comment': 'Участники мероприятий и их статус',
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_change', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.events')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.users')),
            ],
            options={
                'db_table': 'activity_log',
                'db_table_comment': 'История изменений баллов для графиков активности',
            },
        ),
        migrations.CreateModel(
            name='EventTags',
            fields=[
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.events')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.tags')),
            ],
            options={
                'db_table': 'event_tags',
                'db_table_comment': 'Связь мероприятий с тегами',
                'unique_together': {('event', 'tag')},
            },
        ),
        migrations.CreateModel(
            name='EventCategoryLinks',
            fields=[
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.events')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.eventcategories')),
            ],
            options={
                'db_table': 'event_category_links',
                'db_table_comment': 'Связь мероприятий с категориями',
                'unique_together': {('event', 'category')},
            },
        ),
    ]
